### ISSUE TITLE
[feature request] add .date() of last commit

### ISSUE THREAD

**Issue by derwok** [kurttheviking/git-rev-sync-js#12]
Please add a method to get the date of the current git version (date of last commit).
Similar to the output of:

```
git log --no-color -n 1 --pretty=format:"%ad" --date=format:"%FT%TZ"
```

Would be great.
;-)

Thanx. WOK.

**Comment by jantimon** [comment]
@derwok would #21 work for you?

**Comment by kurttheviking** [comment]
closing; adding `#date` function; let me know if you were hoping for something different

**Comment by derwok** [comment]
Thanks a lot! Works great!
