### ISSUE TITLE
Doesn't work with git submodules

### ISSUE THREAD

**Issue by henrikra** [kurttheviking/git-rev-sync-js#13]
When you you have 2 repos: one is parent repo and one is submodule of parent repo this package doesn't work. It is because plugin always searches for .git folder. Working on submodule it doesn't work because submodule has .git FILE. This file tells where the actualy git folder is located for submodule. 

If you want to demo this your self: do 2 repos. Make other submodule as parent module. Then try to use your package in submodule's folder. :) Tell me if you need more details

**Comment by kurttheviking** [comment]
Thank you for letting me know; I don't work with submodules much so I've never encountered this myself but your explanation makes sense to me.

Do you have a suggested way to address this issue? I'd welcome a PR with appropriate fixes.

**Comment by henrikra** [comment]
I could try fixing it. So should i fork thos repo or should you add me as collabrator?

**Comment by kurttheviking** [comment]
Sorry for the very long delay; I just added you as a collaborator. If you'd rather go the fort & PR route that's fine, just let me know.

**Comment by henrikra** [comment]
I added pull request for this https://github.com/kurttheviking/git-rev-sync/pull/22 :)

**Comment by kurttheviking** [comment]
@henrikra merged and published as [`1.8.0`](https://github.com/kurttheviking/git-rev-sync/releases/tag/v1.8.0) &ndash; feel free to upgrade, test, and let me know it works. Thanks!

**Comment by henrikra** [comment]
This should work 100% when my pr is merged https://github.com/kurttheviking/git-rev-sync/pull/23 :+1:

**Comment by kurttheviking** [comment]
closing; pr merged
