### ISSUE TITLE
Use "git rev-parse --short HEAD" to get short hash

### ISSUE THREAD

**Issue by bragma** [kurttheviking/git-rev-sync-js#17]
Hi, thanks for this module. I've noticed you fiddle with files for getting the long hash, then get a substring of it to return the short version. This is not always correct because even if unlikely, it may happen that 2 different hashes have the same starting 7 characters.
If you check the documentation for "--short" you'll see that it always returns an unique value instead (if it is not, it will make the returned hash substring longer).
Please stick with the git commands, it is safer! ;)

**Comment by kurttheviking** [comment]
@bragma thanks for the comment! Yeah the mucking with the file system is to support a variety of edge cases on Windows which may or may not have `git` installed locally. That said, I'm not opposed to a rewrite that uses a shell module to simply call `git rev-parse --short` and return the output. With work and other projects I haven't had time for that refactor.

So, I'm going to close this issue but I will absolutely take that into consideration for the next major release.
