### ISSUE TITLE
Add --first-parent to tag()

### ISSUE THREAD

**Issue by tiberiuzuld** [kurttheviking/git-rev-sync-js#27]
Hi @kurttheviking ,

Please add the option  `--first-parent` to `gitRevSync.tag()`  describe command. 
Option details is [here](https://git-scm.com/docs/git-describe)

This option will return the tag which originated on the current branch, currently if I make a hotfix in the master and merge backwards in develop the hotfix tag will be returned by `gitRevSync.tag()` instead of the dev tag.

Example:
Develop: 1.3.0-dev
Master: 1.2.1

After merge from master to develop. On develop branch the tag will be 1.2.1

**Comment by kane-mason** [comment]
I am also facing this issue and could use a fix

**Comment by kane-mason** [comment]
Probably better to have an "options" parameter for the tag() function for those of us who want to do this

**Comment by tiberiuzuld** [comment]
Hi @kurttheviking ,
Added method `tagFirstParent` so there is no breaking change.

**Comment by kurttheviking** [comment]
@tiberiuzuld thanks; i'll take a look later today

**Comment by kurttheviking** [comment]
closing as  complete
