### ISSUE TITLE
refactor for node 6+

### ISSUE THREAD

**Issue by kurttheviking** [kurttheviking/git-rev-sync-js#35]

**Comment by Zertz** [comment]
If this hasn't been taken on yet, I can take care of it!

**Comment by kurttheviking** [comment]
@Zertz sure; glad to have the help. i think the primary challenge will be to maintain functionality in the various settings currently supported -- git submodules, and so on.

**Comment by Zertz** [comment]
Are there tests for these special cases?

**Comment by kurttheviking** [comment]
no, but most of the logic can be see in the [`git.long` code path](https://github.com/kurttheviking/git-rev-sync-js/blob/c999c068fd4234fca7a8d20323675139af0f53fb/index.js#L91)

**Comment by septs** [comment]
This is my code refactoring implementation.
https://github.com/NiceLabs/git-rev
