### ISSUE TITLE
How to specify short hash length example?

### ISSUE THREAD

**Issue by surfjedi** [kurttheviking/git-rev-sync-js#41]
Hi,

I am trying to use the specifiy short hash length of 8 to match git. But I get "Cannot read property 'join' of null" errors.

That using stuff like:
git.short(8)
git.short(null, 8)

I don't want to specify a different repo, just the exactly repo im in

Any Ideas?

**Comment by kurttheviking** [comment]
I think that was a bug; small patch shipped as `v1.11.2` &ndash; check it out and let me know if it works; if so, I'll close this issue out
