### ISSUE TITLE
No way to get "dirty" status?

### ISSUE THREAD

**Issue by LorenzGardner** [kurttheviking/git-rev-sync-js#9]
something like the results of 

```
git describe --always --dirty
```

could be useful. Maybe have .tag append "dirty" on the end?

**Comment by LorenzGardner** [comment]
I made a fork with a suggested impl in hopes of making a pull request, but that doesn't seem possible to create a pull request?

anyway check out https://github.com/LorenzGardner/git-rev-sync/commit/b520d30c3d762f83c73c033e369db97c497e5e57

**Comment by kurttheviking** [comment]
@LorenzGardner thanks for the note; I'll take a look -- it should be possible to PR; several people have submitted enhancements

If for some reason it's not working, I can certainly take a look at your branch directly

**Comment by LorenzGardner** [comment]
Ok. Managed to sort my pull request woes out.

**Comment by kurttheviking** [comment]
accepted PR; will review and publish later today

**Comment by kurttheviking** [comment]
@LorenzGardner just published this as `1.6.0`; let me know if you have any trouble upgrading

**Comment by LorenzGardner** [comment]
I'm not seeing it

```
https://registry.npmjs.org/git-rev-sync
{"latest":"1.5.1"}
```

**Comment by kurttheviking** [comment]
ack; sorry about that... you mean i have to `npm publish` to publish? got it! :wink:

**Comment by LorenzGardner** [comment]
Thanks. Got it.
